name: Run System Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20 # Adjust the Go version as needed

      - name: Cache Go Modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install Dependencies
        run: |
          go mod tidy
          go mod download

      - name: Run REST API
        run: |
          cd cmd
          nohup go run main.go &
          sleep 5 # Allow time for the REST API to start

      - name: Run System Tests
        run: |
          cd systemTesting
          go test -v ./...


