name: Run System Tests

on:
  push:
    branches:
      - main # Or your target branch
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    services:
      restapi:
        image: golang:1.20 # Replace with your Go version
        ports:
          - 8080:8080
        options: >-
          --entrypoint /bin/bash
        volumes:
          - .:/app

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20 # Replace with your Go version

      - name: Install Dependencies
        run: |
          cd /app
          go mod tidy
          go mod download

      - name: Run REST API
        run: |
          cd /app/cmd
          nohup go run main.go &
          sleep 5 # Give the server time to start

      - name: Run System Tests
        run: |
          cd /app
          go test -v ./systemTesting/... -run SystemTest

